### ISSUE TITLE
Remove dependency on core

### ISSUE THREAD

**Issue by hammer** [biocaml/biocaml#147]

**Comment by hammer** [comment]
@agarwal why was this issue closed? We're hitting long build times w/ `Core` and this project is the only one that depends on it. Can y'all investigate using `Core_kernel` or even `Base`? cc @ihodes

**Comment by pveber** [comment]
@hammer Could you specify the part of biocaml you're using? It would help to know what can be done about that.

**Comment by hammer** [comment]
@ihodes most recently was using FASTA parsing I believe https://github.com/hammerlab/ogene/blob/master/src/ogene.ml

**Comment by agarwal** [comment]
> investigate using Core_kernel or even Base?

I suspect this is feasible and we discussed with @smondet quite a few months ago the option of creating what I've been calling "pure" libraries. Such a library could depend on just Core_kernel or the new Base. @pveber just started it (but called it "base" instead of "pure". We should stabilize on a name choice. It's already getting awkward to qualify every use of "base" as "the base sub-library of project foo" vs "JS's Base").

The value of this is really that it is js_of_ocaml (and hopefully Bucklescript) compatible. I'm not sure what affect this has on compilation time. Does Core proper really take much longer to compile than Core_kernel/Base.

**Comment by pveber** [comment]
@hammer I'm guessing that when you mention long compilation times, you're referring to core's compilation when upgrading through opam, not biocaml's right?

I also think that `biocaml.base` or even `biocaml.unix` could depend only on `core_kernel`. As for JS's `base`, I'd rather wait for an official release and a proper explanation of how it differs from `core_kernel`. But indeed, that may be a very appropriate solution in the long run.

**Comment by rleonid** [comment]
`Biocaml` compiles if we `s/core/core_kernel/` [here](https://github.com/biocaml/biocaml/blob/master/myocamlbuild.ml#L46), can we move this issue incrementally forward by changing the opam dependency to just [core_kernel](https://github.com/biocaml/biocaml/blob/master/opam#L37) ?

**Comment by rleonid** [comment]
Also, is keeping 'ocaml-version >= "4.01.0"' important? I haven't switched to that version to test `core_kernel`.

**Comment by pveber** [comment]
@rleonid I find this rather suspicious you can compile only with the change you mention: there is an `open Core.Std` statement at the beginning of every module in `biocaml.unix`, and the `Sam` module uses `Date` and `Time` which are not included in `core_kernel`. Have you run a `make clean` after changing `myocamlbuild.ml`?

I started a branch a few days ago to adress these changes, and indeed `biocaml.unix` compiles with `core_kernel`. Only issue is that `biocaml.unix` depends on `future` which depends on `core`, not `core_kernel`. We discussed with @agarwal and decided to remove the dependency on `future`. I can do this in the next few days.

**Comment by rleonid** [comment]
@pveber you must be right. I just compiled biocaml "without" `core_kernel` too! The build must be resolving the dependency through `future.unix` ?

I look forward to your PR, I don't mind working with `core` at the moment. Just tried to address this issue while in `biocaml`.

**Comment by pveber** [comment]
With 578d588, `biocaml` now only optionally depends on core (but still requires `core_kernel`). The `opam` file has been updated, so starting from a fresh switch, an `opam install biocaml` should not install `core` anymore. When installing `lwt` or `async`, `biocaml` gets recompiled to add support for these libraries.

I'm closing the issue now, but feel free to reopen if you encounter a problem.
