### ISSUE TITLE
link in C stubs

### ISSUE THREAD

**Issue by agarwal** [biocaml/biocaml#151]
New build system doesn't handle the C file at all, so currently the compiled libs can't actually be used. I'm unsure how to fix it. Here's what I'm trying manually:

First I compile most of the code by doing `omake`. Then:

```
$ cd _build/lib/unix
$ ocamlc -c pwm_stub.c
$ ocamlc -c mzData_stubs.c
$ ocamlc -a -custom -o ../biocaml-unix.cma pwm_stub.o mzData_stubs.o ../biocaml_unix.cmo
```

Now I thought the resulting cma would have the C stubs linked in, but loading it into the toplevel gives:
```
Error: The external function `biocaml_pwm_scan' is not available
```

I'm still missing something. I'd prefer to avoid `ocamlmklib` because it is yet another level of indirection.

**Comment by pveber** [comment]
How about using `ocamlmklib` with `-verbose` option to see what rules you have to implement in omake?
