### ISSUE TITLE
Beginner Contribution Opportunities List

### ISSUE THREAD

**Issue by kanishka-azimi** [biocaml/biocaml#179]
I'm hoping to build out a list of short tasks that beginners can contribute below. Feel free to reply with tasks that come to mind and I will fold into this list.

- [ ]  Task one

**Comment by pveber** [comment]
Hello @kanishka-azimi,
Thanks for your initiative, but I'm not keen on maintaining such a list. If anyone would like to contribute, please open a specific issue or PR and I'll happily review the code. Any topic related to computational biology is welcomed, no need to be shy.

**Comment by kanishka-azimi** [comment]
Definitely defer to your preference, since I am new here. I was trying to imitate the success rust-bio repo has had with this. Will close this issue, and create individual ones as I get more familiar with biopython and rust-bio.

**Comment by agarwal** [comment]
@kanishka-azimi I have some ideas. I can create new issues about them and/or we can also have a call to discuss. Thanks.

**Comment by kanishka-azimi** [comment]
Sounds good, whatever is most efficient for you to transmit ideas.

I think I'm most motivated for ideas that biologists (who know nothing about ocaml) will actually install and use as part of a workflow (distribute CLI's to bioconda?) that might also intersect with algorithm implementations.
