### ISSUE TITLE
implement VCF file parser

### ISSUE THREAD

**Issue by agarwal** [biocaml/biocaml#60]

**Comment by iskandr** [comment]
Did this ever end up as a PR?

**Comment by agarwal** [comment]
No.

**Comment by iskandr** [comment]
Oh, just found that there's a VCF parser in Biocaml now: https://github.com/biocaml/biocaml/blob/master/lib/unix/vcf.ml

I guess you can close this issue?

**Comment by agarwal** [comment]
Oops. Sorry for my wrong answer before. Yes I do recall this. I don't know if anyone's ever used it though. Perhaps you can confirm that it works before we close the issue.

**Comment by iskandr** [comment]
I'll check it out next week, I was just checking out Biocaml while procrastinating having to re-learn the MDtag spec.

**Comment by agarwal** [comment]
ok, sounds good.

**Comment by ihodes** [comment]
It's very close to working for the VCF I'm testing it on now. I'm more than happy to address these issues, too (are you still merging in PRs?) will have a PR shortly.

1. the module is splitting on spaces instead of tabs; the spec calls for the header and data lines to be tab-delimited; this is a trivial change
2. also trivial; this exns when QUAL is missing (i.e. ".")

There may be some other lurking issues, but so far everything else seems to work just fine (once I figured out how to use Tfxm to use this module in the first place).

**Comment by ihodes** [comment]
It might also be useful to discuss how to handle multiple versions of a standard; 4.2 has been out a while, and though most callers output 4.1 still, it's probably important to support both. Have you put any more thought into this?

**Comment by agarwal** [comment]
> are you still merging in PRs?

Yes, definitely.

> once I figured out how to use Tfxm

We're aiming to remove Txfm, so it is also okay to disregard it in new modules. Just provide a blocking API if you want for now, and we can incrementally add support for non-blocking operations in each module when someone has a need for it.

**Comment by agarwal** [comment]
> It might also be useful to discuss how to handle multiple versions of a standard

How about we structure the API like this:

```ocaml
module Vcf = struct
  module V4_1 = struct
    ... 
  end

  module V4_2 = struct
    ... 
  end
end
```

**Comment by pveber** [comment]
Another option Ashish and Sébastien used was to define a type representing the settings for the parsing. For instance, in the case of GFF we have:
```ocaml
module Tags: sig

  type t = {
    version: [`two | `three];
    allow_empty_lines: bool;
    sharp_comments: bool;
  }
...
end
```
Typically the parsing function would take an (optional) `Tags.t` argument. I think this scheme is lighter for users. Of course this makes sense if the parser can reasonably output the same type for the two versions of the format. If not, then Ashish's solution above would be preferable.

**Comment by ihodes** [comment]
This can probably be closed now that https://github.com/biocaml/biocaml/pull/159 is in; I just opened https://github.com/biocaml/biocaml/issues/161 to track writing VCFs.

**Comment by agarwal** [comment]
Okay, so closing this issue. We still need to improve the type definitions, e.g. the names all have a `vcf_` prefix, which doesn't follow our conventions. I have an internal VCF parser that I will try to merge soon.

**Comment by ihodes** [comment]
@agarwal that'd be great to have; if possible, it'd be nice to have access to the metadata of a VCF as well; I'll hold off on #161 for now.

**Comment by agarwal** [comment]
Yes, I am parsing the metadata lines also. The only reason I'm waiting to merge is because I'd like to first finish up the new build, going on in [solvuu_build](https://github.com/solvuu/solvuu_build/commits/v0.0.3-dev). Yes, the lack of a good build script is still hindering our progress... sigh.
